services:
    app:
        build: .
        ports:
            - '8002:8000'
        volumes:
            - '.:/app'
        environment:
            DB_HOST: mysql
            DB_DATABASE: db_menu
            DB_USERNAME: root
            DB_PASSWORD: secret
            PHP_CLI_SERVER_WORKERS: 4
        depends_on:
            mysql:
                condition: service_healthy

    mysql:
        image: mariadb:lts
        environment:
            MARIADB_ROOT_PASSWORD: secret
            MARIADB_DATABASE: db_menu
        ports:
            - '3307:3306'
        volumes:
            - 'db:/var/lib/mysql'
        healthcheck:
            test: ['CMD', 'healthcheck.sh', '--connect']
            interval: 5s
            retries: 10

volumes:
    db:
